__LOCAL_LOG__ {
    weekly
    rotate 26
    compress
    delaycompress
    missingok
    notifempty
    dateext
    dateformat -%Y-W%V
    olddir __ARCHIVE_DIR__
    create 0600 __USER__ __USER__
    copytruncate
}
